
package cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServiciosWebService", targetNamespace = "http://servidor/", wsdlLocation = "http://localhost:8080/WS/ServiciosWeb?wsdl")
public class ServiciosWebService
    extends Service
{

    private final static URL SERVICIOSWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cliente.ServiciosWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cliente.ServiciosWebService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/WS/ServiciosWeb?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/WS/ServiciosWeb?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICIOSWEBSERVICE_WSDL_LOCATION = url;
    }

    public ServiciosWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosWebService() {
        super(SERVICIOSWEBSERVICE_WSDL_LOCATION, new QName("http://servidor/", "ServiciosWebService"));
    }

    /**
     * 
     * @return
     *     returns ServiciosWeb
     */
    @WebEndpoint(name = "ServiciosWebPort")
    public ServiciosWeb getServiciosWebPort() {
        return super.getPort(new QName("http://servidor/", "ServiciosWebPort"), ServiciosWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiciosWeb
     */
    @WebEndpoint(name = "ServiciosWebPort")
    public ServiciosWeb getServiciosWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor/", "ServiciosWebPort"), ServiciosWeb.class, features);
    }

}
